BOARDS_PER_PAGE = 10

THREADS_PER_PAGE = 10
LAST_POSTS_COUNT = 3

MAX_FILES_COUNT = 4
MAX_FILES_SIZE_MB = 5
MAX_FILES_SIZE = MAX_FILES_SIZE_MB * 1024 * 1024

EXPIRATION_DAYS = 1

REPORTS_PER_PAGE = 20

BANS_PER_PAGE = 20